### ISSUE TITLE
integration with cliphist

### ISSUE THREAD

**Issue by pd2s** [philj56/tofi#102]
https://github.com/sentriz/cliphist#faq 
Hi, If this possible to do the same with tofi?
I mean do not display numbers.
Sorry, english is not my native language

**Comment by philj56** [comment]
I assume you mean hiding the first column? So the same as `fzf --with-nth` or `rofi -display-columns 2`?

Currently that's not possible with tofi - there was a little bit of discussion on this in #52, but basically I don't want to add text processing stuff.

I didn't think of it before, but it might be nice to instead have a `--print-index` option or similar (and it should be simple to implement). Then you could do something like
```sh
#!/bin/sh

list=$(cliphist list | cut -f2-)
index=$(printf "%s" "$list" | tofi --print-index)
if [ -n "$index" ]; then
	printf "%s" "$list" | awk "NR==$index {print; quit}" | wl-copy
fi

```

**Comment by pd2s** [comment]
it would be really cool to see something like this

**Comment by philj56** [comment]
Good timing, I've just pushed it in 6060daaee163918f97af4db09bba9a7f9272d6c1. The script from above needs a little bit of tweaking as cliphist doesn't work quite how I thought it did, but the following seems to work fine:
```sh
#!/bin/sh

list=$(cliphist list)  # Original list for reuse in lookup
trimmed=$(printf "%s" "$list" | cut -f2-)  # List without leading numbers
index=$(printf "%s" "$trimmed" | ~/Documents/coding/tofi/release/tofi --print-index=true)
if [ -n "$index" ]; then
	# Use index to find correct line in original list
	printf "%s" "$list" | awk "NR==$index {print; quit}" | cliphist decode | wl-copy
fi
```

**Comment by pd2s** [comment]
it works like a charm! thanks!

**Comment by vrumger** [comment]
@philj56 it returns the wrong index if you use the search

**Comment by philj56** [comment]
@vrumger Whoops, you're right! Sorry it took so long, fixed in 548de1f8c63d4a088400e724a37d483656a2c645.

**Comment by yqlbu** [comment]
Hmmm, seems like it is not compatible with the latest ver. of tofi.

```console
awk: cmd. line:2: NR==# Autosleep {print; quit}
awk: cmd. line:2:     ^ syntax error
error in "decode": decoding: extracting id: input not prefixed with id⏎ 
```

**Comment by bitterhalt** [comment]
Sorry for pumping old issue

> Good timing, I've just pushed it in [6060daa](https://github.com/philj56/tofi/commit/6060daaee163918f97af4db09bba9a7f9272d6c1). The script from above needs a little bit of tweaking as cliphist doesn't work quite how I thought it did, but the following seems to work fine:
> 
> ```shell
> #!/bin/sh
> 
> list=$(cliphist list)  # Original list for reuse in lookup
> trimmed=$(printf "%s" "$list" | cut -f2-)  # List without leading numbers
> index=$(printf "%s" "$trimmed" | tofi --print-index=true)
> if [ -n "$index" ]; then
> 	# Use index to find correct line in original list
> 	printf "%s" "$list" | awk "NR==$index {print; quit}" | cliphist decode | wl-copy
> fi
> ```
Sorry for pumping this old issue!

```
This looks like it is working but it gives error: 
awk: cmd. line:2: NR==# Autosleep {print; quit} awk: cmd. line:2:     ^ syntax error error in "decode": decoding: extracting id: input not prefixed with id
```
