### ISSUE TITLE
[Bug]nautilus and gnome-disks require two operations to start

### ISSUE THREAD

**Issue by DreamMaoMao** [philj56/tofi#113]
the following operations need to be repeated twice each time when i want to start thet two applications:
operations of start nautilus (same for gnome-disks):
1. Shortcut keys call out the panel
2. key input 'file'
3. Select file and press Enter

**Comment by DreamMaoMao** [comment]
![image](https://github.com/philj56/tofi/assets/30348075/e7507d51-7a27-4498-b0c4-d08fbebcbe02)
According to my test, if the desktop file of the application has the option **DBusActivatable=true**, tofi will start the application unstably, and often need to operate twice to start the application. rofi and wofi will not have this problem when starting these applications.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/philj56/tofi/assets/30348075/cfe77bef-f116-445b-a835-610d439b4359)
When I uncheck this option, tofi can start these applications normally, but I don’t know what consequences unchecking this option will have, and there are many applications that need to uncheck this option for rofi to start them normally.

**Comment by mcsimw** [comment]
I noticed like nautilus will launch without any problems after u launch it twice initially, at least for a little while and then again u have to launch it twice for it to open. It is annoying.
