### ISSUE TITLE
[Feature Request] A flag which make tofi write the search prompt in stdout

### ISSUE THREAD

**Issue by nimaaskarian** [philj56/tofi#126]
`tofi` searches inside the stdin lines and you can't enter if there's no matches.  
I suggest having a flag or a mode that make tofi output the search prompt. It's useful for some scripts.

**Comment by philj56** [comment]
Hey, sorry for the delay.

This already exists in tofi, in the form of `--require-match`. You can make it act as a simple input box with the following:

`tofi --require-match false </dev/null`
