### ISSUE TITLE
A border around the selected item

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#13]
![image](https://user-images.githubusercontent.com/13646790/181097559-9247f04b-584c-415d-b5a5-03cdfef78721.png)
As it currently stands with how little there is to the selected text, it looks a bit off, if there was a bit of padding to the background color on the left and right i think it would look a lot better, thoughts?

edit: alternatively you could make the selection background go all the way to the left/right of the selection in the window, which would also look a lot better IMO, or have a fixed width

**Comment by philj56** [comment]
Yep, a small amount of padding would be better. I'm not sure about going all the way left to right - doesn't really work in horizontal mode, but we'll see. Either way, I need to do some other cleaning up of the rendering code before I can do this, as currently it's clipped such that slanted fonts get cut off:
![slant](https://user-images.githubusercontent.com/13610623/181239398-90366350-0b36-4d8f-93ce-084c488fdc37.png)

**Comment by Kommynct** [comment]
Yeah obviously left to right is only good for vertical mode, very true, but I do think it would look nice for a lot of vertical setups, I dunno, I think I'd prefer the look of that but definitely padding would be a good start, you could even make it so that the padding can be a percentage of the available space for the entry, and 100% fills everything. Up to you obviously.

**Comment by philj56** [comment]
Alright, I've added a `--selection-padding` option in 1bce3f1db092c2aec92da738c6b4d090405b37d3. It only takes pixels as an argument, but you can just specify a number larger than you need if you want it to go all the way left-right. Note that it doesn't draw over the padding given to `--padding-*`, as all draws are clipped to occur within that area.

**Comment by Kommynct** [comment]
Coul you make it so -1 is infinite?

**Comment by philj56** [comment]
Yup, done in b5c2f630fd57dd6737ebbd8b0ea9b733a7aff4da.

**Comment by Kommynct** [comment]
Thank you so much!!
