### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by OlaoluwaM** [philj56/tofi#132]
How do you uninstall after building and installing from source

**Comment by Kacper-Kondracki** [comment]
I think you can uninstall it by undoing the install steps that were done in meson.build

https://github.com/philj56/tofi/blob/master/meson.build

**Comment by philj56** [comment]
Yeah, that's pretty much it. The full list of stuff that gets installed (with paths for an Arch system) is:
- The `tofi` binary, `tofi-run` & `tofi-drun` symlinks ('/usr/bin').
- The `tofi.1`& `tofi.5` manpages, and `tofi-run.1`, `tofi-drun.1` symlinks (`/usr/share/man/man{1,5}/`).
- The license (`/usr/share/licenses/tofi`).
- The example config file (usually in `/etc/xdg/tofi/config`).
- The bash completion file (`/usr/share/bash-completion/completions/tofi`)

**Comment by Kacper-Kondracki** [comment]
It would be also reasonable to add "uninstall" target to meson to automate it.
