### ISSUE TITLE
For some reason you need to launch the application twice to be able to launch any GTK app.

### ISSUE THREAD

**Issue by RyanOrigens** [philj56/tofi#138]
For some reason you need to launch the application twice to be able to launch any GTK app.

I'm running hyprland....

**Comment by bencollerson** [comment]
GIMP 2.10.36 worked fine after being launched once for me on dwl.

What GTK app are you launching?

**Comment by RyanOrigens** [comment]
It seems to be GTK 4 apps.

**Comment by bencollerson** [comment]
I have tried running nautilus (44.2.1-2) and gnome-weather (45.0-1) and they both launch immediately. I am using dwl, but can you try using sway to launch these apps?

**Comment by RyanOrigens** [comment]
It also didn't work out on sway.

**Comment by mb720** [comment]
Does this help?

    tofi-drun --drun-launch=true

This works for me on Arch with Sway.

**Comment by RyanOrigens** [comment]
Hi mb, 

Thank you for trying to help!

Unfortunately, this isn't the problem i'm running into, the app itself works, i'm just having to execute twice GNOME applications.

**Comment by gitgoggles** [comment]
I always have to launch TeamSpeak 5 twice, is that GTK? It's the only program I have that does it.
