### ISSUE TITLE
Example configuration file

### ISSUE THREAD

**Issue by CRAG666** [philj56/tofi#16]
I want to use this project but I would like to see an example configuration file to start from there

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
There are some example themes on the README page. Further options are explained below.

**Comment by philj56** [comment]
Yeah, the example themes and `tofi(5)` man page cover it pretty much, but it might be nice to have a documented example with the defaults - it's probably fairly easy to autogenerate one from the man page.

**Comment by philj56** [comment]
Ok, I've added an [example config file](https://github.com/philj56/tofi/blob/master/doc/config) (not autogenerated) loaded with the defaults, which gets installed to `/etc/xdg/tofi/config`.
