### ISSUE TITLE
Flatpak .desktop not detected despite $XDG_DATA_DIRS

### ISSUE THREAD

**Issue by Interpause** [philj56/tofi#163]
This is not a dupe of #81 or #115. I am using `tofi-drun` and have deleted `~/.cache/tofi-drun` multiple times. While doing so helped some previously missing programs show up, flatpak applications still do not show up.

```sh
echo $XDG_DATA_DIRS
>>> /home/jh/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /nix/store/pwmiaglhbyaiyfhc0fmg4jdjblxvmbys-desktops/share /home/jh/.nix-profile/share /nix/profile/share /home/jh/.local/state/nix/profile/share /etc/profiles/per-user/jh/share /nix/var/nix/profiles/default/share /run/current-system/sw/share
```

```sh
ls -l /var/lib/flatpak/exports/share/applications/
>>> total 12
lrwxrwxrwx 1 root root 113 May  1 15:48 com.atlauncher.ATLauncher.desktop -> ../../../app/com.atlauncher.ATLauncher/current/active/export/share/applications/com.atlauncher.ATLauncher.desktop
lrwxrwxrwx 1 root root 115 May  1 16:00 com.github.tchx84.Flatseal.desktop -> ../../../app/com.github.tchx84.Flatseal/current/active/export/share/applications/com.github.tchx84.Flatseal.desktop
-rw-r--r-- 1 root root  13 May  1 16:00 mimeinfo.cache
```

Any help would be appreciated. Thanks!

**Comment by Interpause** [comment]
...a reboot and deleting tofi-drun one more time seems to have solved this. Weird.

**Comment by jabuxas** [comment]
I'm having this issue, anyone else?
`/yang/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share` my XDG_DATA_DIRS looks fine..

**Comment by h4rldev** [comment]
For some reason, cache doesn't get updated, you'll have to go to .cache and delete them, I have no idea why. It's bugging me

**Comment by VelocityREST** [comment]
Same  issue except it's for nixpkgs if I use another launcher it works but not for tofi, I also deleted .cache file and still didn't work
