### ISSUE TITLE
[feature] interpret commands w arguments in drun mode?

### ISSUE THREAD

**Issue by amberjennings** [philj56/tofi#171]
One think I liked about rofi was being able to, for example, run `killall steam` from the drun mode. With tofi, I cannot do this - pressing return simply doesn't do anything. Similar behavior in run mode, where it recognizes killall as a command but doesnt like having arguments passed to it. I'd very much like to have this functionality in tofi.

**Comment by paddy-hack** [comment]
Have a look at #34.

**Comment by amberjennings** [comment]
@paddy-hack Thank you!
