### ISSUE TITLE
Repository contains binary

### ISSUE THREAD

**Issue by b1rger** [philj56/tofi#18]
Hi, 
commit https://github.com/philj56/tofi/commit/1c6481e5c630a600d0c2a40069cd4e85f0b11cef adds a binary file (`vgcore.651870`) to the repository, my guess is that this was commited by mistake?

**Comment by philj56** [comment]
:facepalm: Yes indeed, thank you for spotting that! Now I'll have to look into removing it from the history (seeing as it's many times bigger than the whole of the rest of the repository)

**Comment by philj56** [comment]
Ok, I've done the evil thing and force-pushed to master, but it's the only way to remove a file from history (and while tofi's still pre-1.0 and not using feature branches and the like, I'm alright with some minimal breakage). Thanks again for letting me know!
