### ISSUE TITLE
Specify custom history file

### ISSUE THREAD

**Issue by machitgarha** [philj56/tofi#185]
I love tofi, and want to use it for other purposes, like selecting a VPN connection to connect to. However, it isn't possible to do so. It would be nice to have such an option, e.g. `--history-file`.

**Comment by DrVoidest** [comment]
There is in your config put `history-file = /path/to/histfile`

**Comment by machitgarha** [comment]
Ah, my bad, I didn't read the docs carefully. Thanks.
