### ISSUE TITLE
Segmentation fault when cache is not readable

### ISSUE THREAD

**Issue by ardurin** [philj56/tofi#187]
To replicate:
```
touch "${XDG_CACHE_HOME}"/tofi-drun
chmod 000 "${XDG_CACHE_HOME}"/tofi-drun
tofi-drun
```

It seems to be caused by `drun_generate_cached`trying to fclose the `cache` file, which is NULL.

**Comment by philj56** [comment]
Nice catch, thanks for the report! Should be fixed in e2bed7eda881a4273f61742f38eaae6b71daf340.
