### ISSUE TITLE
How do I make the window transparent?

### ISSUE THREAD

**Issue by FurtherSecrets24680** [philj56/tofi#188]
As the title suggests, how can I make the tofi window transparent? There's no option about that in the config documentation.
Is there an alternative way to do it?

![image](https://github.com/user-attachments/assets/13d2f974-e702-4172-bdc3-b88b7c25244f)

**Comment by DrVoidest** [comment]
You need to use the alpha channel to make things transparent I used [this](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4) to pick the right color. I found the following looks nice: background-color=#00000080.

**Comment by FurtherSecrets24680** [comment]
> You need to use the alpha channel to make things transparent I used [this](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4) to pick the right color. I found the following looks nice: `background-color=#00000080`.

Thanks! I was confused because there was no such label of transparency in the config. Didn't know there were hex color codes for transparency.
