### ISSUE TITLE
How is this tiny and simple?

### ISSUE THREAD

**Issue by apprehensions** [philj56/tofi#199]
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
C                           26      8090      706       997     6387       1499
C Header                    24       737      145        27      565          2
[...]
```
This project is nearly ~7000 SLOC, and ~8900 LOC.

Compared to dmenu and other menu clones, this is almost three times the size.

**Comment by itshog** [comment]
Maybe because performance and code quality aren't measured in lines of code?

**Comment by apprehensions** [comment]
Yes, so why is lines of code mentioned? Using terms such as 'tiny' to describe size, but not performance or code quality?

**Comment by itshog** [comment]
> Yes, so why is lines of code mentioned? Using terms such as 'tiny' to describe size, but not performance or code quality?

Where are lines of code mentioned? Also, I believe that "tiny" and "simple" are used to describe the usage paradigm of programs like tofi (but also of similar programs like dmenu, fuzzel, bemenu, wmenu etc.), which tries to adhere to the philosophy of "do one thing, do it well" (avoiding feature creep, promoting integration with other simple utilities etc.). Maybe "tiny" isn't the first adjective that comes to mind when thinking about this project, as this goal is shared by many similar programs and IMO the distinctive feature of tofi is speed/performance, but I don't think that putting "tiny" in the description is deceiving in any way.

Also, if we really want to talk about size, the tofi binary on my system is 124K...surely not what I'd describe as a "bloated" program. If you think that something in the source code could be done in a more concise way, feel free to make a PR; complaining about lines of code as if this number alone was a significant metric isn't helping anyone.

**Comment by apprehensions** [comment]
> (but also of similar programs like dmenu, fuzzel, bemenu, wmenu etc.), which tries to adhere to the philosophy of "do one thing, do it well" (avoiding feature creep, promoting integration with other simple utilities etc.).

You realize that bemenu isn't that? It is full of feature creep by having a client-server library and being far away from what it was meant for, while programs such as dmenu not only adhere to UNIX philosphy, it also adheres to the suckless philosphy, which emphasizes code size. This project, while it is simple in terms of usage, it is not tiny in *codebase*. I think replacing it with 'performant' would be a better term as using 'tiny' would be misinterpreted as codebase to an audience of suckless philosphers, which is why I made this issue.
