### ISSUE TITLE
Proper scrolling

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#20]
Right now when you scroll to the bottom of tofi it doesn't give you the next entry... it goes back to the top, regardless of how many entries there should be.

**Comment by Kommynct** [comment]
Awesome, and with that (assuming this works perfectly I haven't tested it yet I'm not home) tofi is the perfect launcher for me. Thank you so much for the hard work!

**Comment by philj56** [comment]
No problem! Thanks for all the suggestions, it helps motivation when you know someone's actually getting some use out of what you're doing :)
