### ISSUE TITLE
Make 0 width/height be the minimum while showing all results

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#22]
0 width/height should be the smallest possible size that displays everything without cutting anything off by default to maximize performance, I think that'd be a better default, although much less useful with height (in vertical mode, width in horizontal)

-1 should be fullscreened

This will let me use tofi for power management while making the power management window as small as possible, I could set it to be a specific number of pixels, but that would mess with scaling.

**Comment by philj56** [comment]
Ah, I don't really think this is possible for a couple of reasons:

- You can't know how big text is going to be before drawing it, but you need a canvas to draw on. Tofi would therefore need to draw the whole first frame to some empty canvas (that's big enough to hold the text), then measure it, then create a window the right size and copy over the drawn text. This would probably slow down startup considerably, which is exactly what I'm trying to avoid, and make the code more complicated.
- This can't work with `--num-results=0` auto-detecting how many results can fit in the window, as you'd have a chicken-and-egg problem.

For fullscreen, you can already just use percentages for some values e.g. `--width=100%`, and it'll do the right thing (the [manpage](https://github.com/philj56/tofi/blob/master/doc/tofi.5.md) has the rest of them listed). That should hopefully also take care of any scaling problems.

In an extreme case, you could even do something like using
`swaymsg -t get_outputs | jq '.[] | select(.focused==true) | .name'` to get the name of the current output, then bind your keyboard shortcut to a script that starts tofi up with different configs for different screens.
