### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by akselaase** [philj56/tofi#23]
First off, thanks for making tofi, it's great! As a feature request, it would be nice to have support for fuzzy string matching like how `fzf` or the VS Code command prompt works. For instance, the string `mm` would match the word `Mattermost`, and `vc` would match `Visual Studio Code`. 

I found a couple of resources explaining the algorithm and implementation [for fzf](https://github.com/junegunn/fzf/blob/master/src/algo/algo.go) and [for VS Code](https://github.com/microsoft/vscode/blob/main/src/vs/base/common/fuzzyScorer.ts).

**Comment by philj56** [comment]
Glad you're enjoying it!

I'll have a look into fuzzy matching but I don't particularly have a use for it - my use case is pretty much only ever using `tofi-run` and typing the beginning of the command. Thanks for the links, from those it seems somewhat complex (at least more than the current `strcasestr()` search), but not too bad. Either way, I'll give it a go.

**Comment by philj56** [comment]
Alright, I've added a `--fuzzy-match` option in 8e45592c5703451563eaf4edcd7033f80ce23b53. I found a much simpler fuzzy match in the public domain [here](https://github.com/tajmone/fuzzy-search/blob/master/fts_fuzzy_match/0.1.0/cpp/fts_fuzzy_match.h), and wrote an even simpler (but very nearly as good) version in [fuzzy_match.c](https://github.com/philj56/tofi/blob/master/src/fuzzy_match.c). It's pretty basic, but it works well enough:

![fuzzy](https://user-images.githubusercontent.com/13610623/184453112-8851a873-1f6e-49a9-ba44-d2f6b409dfef.png)

**Comment by philj56** [comment]
I've improved the fuzzy matcher in aaccdaa155a82bc7a98e4f82fc24415d6dd4e4db. It should now always find the best possible match (according to the chosen scoring criteria).

**Comment by akselaase** [comment]
Thank you for taking your time do implement this (and so quickly), it works great!
