### ISSUE TITLE
Percentage values incorrect when fractional scaling is applied

### ISSUE THREAD

**Issue by philj56** [philj56/tofi#24]
There's no way (that I'm aware of) for an application to be aware of a fractional scale factor directly - all of the Wayland protocols (such as [`wl_output_scale`](https://wayland.app/protocols/wayland#wl_output:event:scale)) use integers for the scale factor. Sway achieves fractional scaling (I think) by passing the next largest integer to the application, then scaling it down.

As a workaround for 100% width/height windows, you can pass `--width 0` / `--height 0` to tofi. This will leave the decision of how big to make the window up to Sway, and so as long as you're anchored in the center of the screen in the relevant direction, it'll do the right thing.

Unfortunately, I don't think there's any way to make it so that percentages work with fractional scaling though.

**Comment by philj56** [comment]
Yep, thanks for the reminder - I'll look into this again as soon as support is merged into Sway (https://github.com/swaywm/sway/pull/7242).

**Comment by philj56** [comment]
Alright, support for wp-fractional-scale-v1 has been added in 582825eda792c2612ab6f43a14ccb2bea3aee5d4. Currently, only Kwin, Hyprland and sway-git support this as far as I know.

**Comment by philj56** [comment]
Support for fractional scaling has been released in [v0.9.0](https://github.com/philj56/tofi/releases/tag/v0.9.0).

**Comment by herrvonvoid** [comment]
so, is it supposed to work now, or does that mean that now there's a timeline to fixing this? because this is still an issue for me (archlinux, sway 1.8.1, tofi from aur version 0.9.1-2)

**Comment by philj56** [comment]
@herrvonvoid sorry for the late reply. This is fixed in tofi, but it requires Sway 1.9 which hasn't been released yet (and given Sway's release history, is probably at least a couple of months away). In the mean time, there's not much that can be done, unless you use the latest git version of Sway from the AUR.
