### ISSUE TITLE
readline binds

### ISSUE THREAD

**Issue by samhh** [philj56/tofi#26]
Specifically support for `<C-w>` and/or `<C-u>` would match dmenu and most other software in this space.

**Comment by philj56** [comment]
Alright, I've added `<C-w>` and `<C-u>` in 7d9a1c9b401e83ea642892535c399f906b2defa6.

I probably need to do some cleanup of the input handling in general. It's currently very bare-bones, as I only really ever use `tofi-run`, type the first few letters of the command, and let history sorting choose the right thing.
