### ISSUE TITLE
Allow arbitrary selection

### ISSUE THREAD

**Issue by samhh** [philj56/tofi#28]
It's possible to reuse dmenu for general searching not against results like so:

```console
$ echo "" | dmenu # enter "foo<Enter>"
foo
```

tofi doesn't appear to support this because it requires a match. I think that's a sane default, but could an option be added to accept the entered text regardless of whether it has a match?

My use case is that I use dmenu/tofi for opening bookmarks, apps, and so on, but also for launching web searches from anywhere, in which case it's really acting more like a plain text input.

**Comment by philj56** [comment]
Yep, that's sensible and easy enough - I've added `require-match` (defaults to true, and is always true in drun mode) in faf685ca266d9cd3e2bb42d2ef105a5577cfcaf1.
