### ISSUE TITLE
Prompt padding

### ISSUE THREAD

**Issue by samhh** [philj56/tofi#29]
I may be glancing over this in `-h`, but something like a `--prompt-padding` would be handy.

```console
$ echo foo | tofi --prompt bar
```

Type anything and there'll be no space after "bar". This means that every use of tofi requires that the prompt is given a trailing space.

**Comment by philj56** [comment]
Yeah makes sense, I agree adding a space to the prompt is a bit of a kludge - I'll add that soon.

**Comment by philj56** [comment]
Alright, I've added `--prompt-padding` in 226b063306291642b9bc9d5df0e54f2886d18486.
