### ISSUE TITLE
Space character

### ISSUE THREAD

**Issue by samhh** [philj56/tofi#30]
Just noticed that tofi doesn't appear to allow space input. Why is that? My use case is alongside `--require-match false`.

Thanks for the resolutions to my other issues by the way! :slightly_smiling_face:

**Comment by philj56** [comment]
It's really just a holdover from me only using `tofi-run`, where a space is meaningless and currently causes there to be no matches (I actually allow spaces in `tofi-drun`).

I guess the correct thing to do here would be to split the input into "words" on spaces, and filter the results by each one. I think that's what dmenu does in any case.

> Thanks for the resolutions to my other issues by the way! :slightly_smiling_face: 

No problem, thanks for the suggestions!

**Comment by samhh** [comment]
Works a treat, thanks again!
