### ISSUE TITLE
config: allow to include files

### ISSUE THREAD

**Issue by primalmotion** [philj56/tofi#32]
I'm using pywal and friends to manage my colorscheme, and it seems that we cannot use multiple config files (or include one into another) with tofi. I would like to be able to do so to separate the color config from the actual config.

Thanks for this great piece of software btw!

**Comment by philj56** [comment]
Yep sounds like a good idea, I've thought about this before but at the time there weren't quite so many options available. I'll have a look at adding `include` as an option.

By the way, you can actually use multiple config files at once currently, but you have to specify all of them on the command line, e.g.:
```
tofi -c config_a -c config_b
```

**Comment by philj56** [comment]
Alright, I've added `--include` in 4801fff08bf3d42361a72e339c59390828983f49. You can specify absolute or relative paths, and passing it on the command line will do the same as `--config` except the default config will still be loaded.

**Comment by primalmotion** [comment]
awesome! Works like a charm. Thanks!
