### ISSUE TITLE
click outside to dismiss

### ISSUE THREAD

**Issue by primalmotion** [philj56/tofi#33]
Currently clicking outside of tofi's window does nothing which conflicts with my muscle memory :) Is it possible to dismiss tofi when clicking outside?

**Comment by philj56** [comment]
I'm not sure, but it's a reasonable suggestion - I'll look into it.

**Comment by philj56** [comment]
Ok, so after some research, it looks like the answer's "not really". The main problem is that Wayland is designed around clients not knowing what's going on with the rest of your screen, so actually detecting a click outside the window directly is impossible. I found a few possible ways to do something similar:

- Dismiss tofi when it loses keyboard focus. This almost does the right thing, except that when the mouse leaves the surface, an immediate `keyboard_leave/keyboard_enter` pair of events are sent as well. To handle this properly, I think I'd have to somehow set a timer on `keyboard_leave/keyboard_enter`, and only quit if a `pointer_leave` isn't seen immediately after. I don't really want to do this however, as it's janky, and I don't think the order of the keyboard/pointer events is well-defined.
- Just accept this, and dismiss tofi whenever it loses pointer or keyboard focus, so moving the mouse off the tofi window would close it.
- Potentially some fudging with popups, which do the right thing? I don't think this is possible though.

So overall I'm not sure - do you have an example of a program that works like this in sway?

**Comment by primalmotion** [comment]
I was sure that rofi was doing this, but actually no, it does not. Thanks for looking into this. If the implementation is janky, I agree that it's better to have no implementation at all.

**Comment by ThaBluNate** [comment]
abenz1267/walker does this. Not sure how.
