### ISSUE TITLE
on Hyprland, tofi always appears on my second monitor

### ISSUE THREAD

**Issue by primalmotion** [philj56/tofi#35]
It does not matter where my mouse is, tofi always show on my second monitor. This does not happen on Sway

**Comment by philj56** [comment]
Alright, this should be fixed in 803b0d14b7ac8ea03105613fa25849d460073357.

**Comment by vaxerski** [comment]
fixed on hyprland's side in https://github.com/hyprwm/Hyprland/commit/2d73da1a79fc32bca62da6e9b79b8525ec42fa9c

**Comment by philj56** [comment]
Oh cool! I had a brief look at Hyprland's code, but I'm not familiar with Wayland server stuff, so didn't find that.
