### ISSUE TITLE
[Feature Request] Add an option to replace input characters with * or _ or something

### ISSUE THREAD

**Issue by ZachIndigo** [philj56/tofi#36]
This is equivalent to dmenu -P, which is useful for having a menu to input passwords for scripts.

**Comment by philj56** [comment]
Alright, this is done in 4f13d9c88e8a00ccb9ba8d5380db2f93d3f67908. I've added it as two separate options: `--hide-input` to control whether to hide or not, and `--hidden-character` to control what gets shown instead.

**Comment by ZachIndigo** [comment]
Thanks! That works for me
