### ISSUE TITLE
feature request: shift-tab 

### ISSUE THREAD

**Issue by marcusatiliusregulus** [philj56/tofi#39]
Please add a mapping shift-tab to go back one entry;
or stop shift from resetting the current selection to the first entry.

It is very common in applications to be able to select the next entry with tab and the previous with shift-tab. since tab works in tofi, one would assume that shift-tab does too, but instead the selections resets and then you cannot simply use the back arrow anymore which is annoying.

Great tool, kr

**Comment by philj56** [comment]
Alright, this should be working in ef585fcbe156e6622222cd4a018776a5e1fb194b. I hadn't noticed that shift/ctrl etc. were resetting the selection, thanks for mentioning that.

I think one of the next things I should do is clean up the keybindings and make them customisable, as it's a bit messy and inflexible right now.
