### ISSUE TITLE
Release v0.1.0 is broken and missing in master

### ISSUE THREAD

**Issue by jirutka** [philj56/tofi#4]
```
meson.build:5:2: ERROR: Expecting rparen got id.
  license: 'MIT',
  ^
For a block that started at 1,7
project(
       ^
```

And the 1da9e9c491ac026e3575df4b36105aeeadb5879c is missing in the master branch – this is really not a good approach for tagging releases.

**Comment by philj56** [comment]
> the https://github.com/philj56/tofi/commit/1da9e9c491ac026e3575df4b36105aeeadb5879c is missing in the master branch

Ah woops, I pushed the tag without the commit. Sorry about that! I'm not particularly familiar with tagging releases.

Should be fixed in [0.1.1](https://github.com/philj56/tofi/releases/tag/v0.1.1).

**Comment by jirutka** [comment]
Thanks! FYI, I’ve packaged tofi for Alpine Linux – [tofi on pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/packages?name=tofi).

**Comment by philj56** [comment]
Hi, I've just done a force push to the master branch (evil I know, but I'd accidentally committed a large binary file right on the v0.3.0 release :facepalm: and while it's still pre-1.0, I'm alright with breaking some bits). I had a look at the alpine package, and I think you'll need to update the sha512 sum in the APKGBUILD for it to work again.  Sorry for the trouble.
