### ISSUE TITLE
Provide option to select top or overlay layer and to enable exclusive zone

### ISSUE THREAD

**Issue by schauveau** [philj56/tofi#40]
Tofi is currently using `ZWLR_LAYER_SHELL_V1_LAYER_TOP`. An option should be provided to use `ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY` instead. 

I see 2 good reasons to use overlay instead of top. 

(1) Some people, like me, configure their status bar (ie. sway-bar, waybar, ...) in the top layer to keep it above the application windows. Unfortunately, that also means that tofi appears below the bar which makes it unusable when anchored at same border than the bar in horizontal mode. 

(2) The overlay layer is visible when running a fullscreen application while the top layer is not.

You should also consider an option to enable the exclusive zone. That would be an effective way to keep tofi and the bar to overlap.

**Comment by philj56** [comment]
Hey, thanks for the info! I agree on using `OVERLAY` vs `TOP` - I mostly just chose `TOP` on a whim, as I couldn't notice any difference in my setup (but the fullscreen point is a good one). I think it should probably just always be set to `OVERLAY` so it's definitely visible, as it already grabs keyboard focus - I don't think you'd ever want tofi to be hidden behind something else.

Regarding the exclusive zone, I'm not sure exactly what needs to be done to get it to work. As an example, I've tried starting up waybar with the following minimal config:
```json
{
	"layer": "top",
	"mode": "dock",
	"modules-left": ["sway/workspaces", "sway/mode"],
}
```
From the [waybar source code](https://github.com/Alexays/Waybar/blob/ae9fb577909b246f0ee7719e2a533737b39b9ca7/src/bar.cpp#L38), this looks like it should end up setting its exclusive zone to the vertical size of the bar (and indeed, everything else gets moved out of the way for it).

The [wlr_layer_shell docs](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_exclusive_zone) make it seem like nothing needs to be done then on tofi's side. The default for the exclusive zone is 0, which apparently means "move me out of the way of other exclusive zone windows". Tofi still shows up on top of / below waybar however (depending on layers). If I add an explicit `set_exclusive_zone(0)`, or even give a positive number for it, I still get the same behaviour. Even starting up two instances of tofi with the dmenu theme, with positive exclusive zones set for each, results in them overlapping.

So yes, I'd like to fix this, but at the moment I'm a bit stuck. I'll look into it some more, but I'd welcome suggestions.

**Comment by schauveau** [comment]
I am able to to open it next to my waybar without overlapping by setting the exclusive zone to 0.  

However, I have to admit that I do not really understand the behavior.  For example, with waybar in TOP layer, tofi in OVERLAY layer and an exclusive zone of 10,  I get tofi above the bar but I also notice that the bar is moved down by a few pixel (as if the exclusive zone was not big enough).  

But I see that you wrote **If I add an explicit set_exclusive_zone(0) **. Did you miss that there is already one at https://github.com/philj56/tofi/blob/master/src/main.c#L1322

Anyways, the best value is a matter of personal preference and probably depends of the layer used by the bar. So the best approach is probably to let people choose the exclusive zone value via an option. The default should probably be set to 0 or -1.

**Comment by schauveau** [comment]
I read the documentation of `iface_zwlr_layer_surface_v1` more carefully and I think that I understand.

Basically, that is

-  -1 means «I do not care»
- 0 means «try not to overlap with other objects in the layer shell»
- a positive value means «reserves that many pixel for my exclusive use» thus pushing the bar and the other windows away.

**Comment by philj56** [comment]
> But I see that you wrote If I add an explicit set_exclusive_zone(0) . Did you miss that there is already one at https://github.com/philj56/tofi/blob/master/src/main.c#L1322

 :facepalm: D'oh, of course you're right! Good catch, I had completely missed that I'd already done that. Yes, then I think I'll do the following:

- Set the layer to always be `OVERLAY` (unless there's some good reason not to)
- Add an `exclusive-zone` option, but keep the default of -1


> I read the documentation of iface_zwlr_layer_surface_v1 more carefully and I think that I understand.

Yes, that was my understanding as well, but I'd confused myself by not noticing that I'd already set the exclusive zone to -1.

**Comment by primalmotion** [comment]
Love it when you stumble upon a problem, go to report an issue, realize someone already reported it, and the fix is already in :) Thanks for your work on tofi!
