### ISSUE TITLE
Benchmark comparison with popular launchers

### ISSUE THREAD

**Issue by timsofteng** [philj56/tofi#42]
Hello. According to readme in repo the main point of tofi is speed. 
May you provide some benchmarks to compare tofi with popular launchers like bemenu, fuzzel, and rofi-wl?
Thanks.

**Comment by philj56** [comment]
Unfortunately I don't really have a good way to benchmark other tools. I did do some in the past but it required quite a bit of source code hacking, and rofi in particular is a huge beast. It really all comes down to fonts - all of those use Pango/Fontconfig for text, so will take at least ~120ms (as mentioned in the [readme](https://github.com/philj56/tofi#options)) to start on my machine.
