### ISSUE TITLE
Open a new terminal when asked to do so

### ISSUE THREAD

**Issue by devgioele** [philj56/tofi#46]
Some programs have a desktop file with the option `Terminal=true` and should be opened in a new terminal window.
[lf](https://github.com/gokcehan/lf) is an example and does not open in a new terminal window.

Is this feature missing and the `Terminal` option ignored?

**Comment by MahouShoujoMivutilde** [comment]
I also use lf, I don't remember exactly where I saw it, but the implementation for finding this terminal basically looks like an giant `if` statement that checks if any of the "popular" (and quite outdated) terminals is installed, and uses one of them.

It doesn't magically know that you prefer, let's say, alacritty. It doesn't know alacritty is a thing.

But what you can do is trick it:

```
# ln -s /usr/bin/alacritty /usr/bin/rxvt
```

...and now it will think that `rxvt` is installed, and will try open that, opening alacritty in reality.

**Comment by devgioele** [comment]
Nice hack, but couldn't it just check for the env var `TERM`?

**Comment by MahouShoujoMivutilde** [comment]
It seems the launch happens via Glib function

https://github.com/philj56/tofi/blob/7bb70c7407f652c584837d651fb9bcdb6b66ff9f/src/drun.c#L345

so it will likely behave the same as if you used `gtk-launch lf.desktop`, hitting the same underlying `if` statement to find the terminal.

[Found it, btw](https://gitlab.gnome.org/GNOME/glib/-/blob/86430a27d26b9b72b02ff0b81eeaa5df0525646c/gio/gdesktopappinfo.c#L2657-2702).

It is a known [Glib issue](https://gitlab.gnome.org/GNOME/glib/-/issues/338).

Notice the issue's age.
Notice the number of closed merge requests, related to it.

And of course

> _Please add Alacritty, you know you want to. This will take at least another decade to get fixed._

Yeaaaah.

> Is there an issue with that?

`TERM` is only defined in a shell started from a terminal, you would want to name it something else, and define explicitly in `.profile` for your shell.

> if the env var is defined and then proceed with some common terminals

Or check the e.g. `$TERMINAL`, if set - launch `$TERMINAL -e app's_exec`, fallback to `g_app_info_launch()`

Maybe, not for me to decide.

**Comment by MahouShoujoMivutilde** [comment]
Well, it does it by getting a process name, so the point stands.

If tofi is launched from non-interactive shell (e.g. from the compositor via hotkey) - this wouldn't get you the preferred terminal either.

**Comment by philj56** [comment]
Yeah, so this is a bit of an annoying point of the desktop file spec. It seems there's no standard way to go about this, so whatever we do is going to have at least one drawback.

> If tofi is launched from non-interactive shell (e.g. from the compositor via hotkey) - this wouldn't get you the preferred terminal either.

Yup, it's unfortunate that we can't use a trick like this here.

> I would first look if the env var is defined and then proceed with some common terminals. Is there an issue with that?

> Or check the e.g. `$TERMINAL`, if set - launch `$TERMINAL -e app's_exec`

Yeah, this is similar to the way [i3-sensible-terminal](https://github.com/i3/i3/blob/next/i3-sensible-terminal) does it. This is a possibility, as tofi already has the ability to grab a list of binaries on the system, so we could just iterate through that list looking for one that exists. The main downsides are:
- It has to be updated every time someone releases a new terminal emulator (not that frequent, but still annoying)
- It may not launch the user's preferred one if they have multiple installed (and they've never heard of `$TERMINAL`, I hadn't before this)
- I don't know if this is still true for any emulators, but I know at least [kitty](https://github.com/kovidgoyal/kitty/issues/502) didn't support `-e` for a short while.

I think the simplest solution may be just to add a `--terminal` option, and prepend that to the command line of the .desktop file whenever `Terminal=true` is set, e.g. `tofi-drun --terminal="xterm -e"`. I could make the value default to the value of `$TERMINAL` or something as well.

**Comment by MahouShoujoMivutilde** [comment]
At the of the end of the discussion you can see that the dev decided to ignore `-e` after all for compatibility: https://github.com/kovidgoyal/kitty/commit/45fc1ace0c2023294a74a8d73955176333bfcf52

`--terminal` option defaulting to `$TERMINAL` sounds nice, I suggest also having more elaborate error for the failed launch:

```c
void drun_launch(const char *filename)
{
	GDesktopAppInfo *info = g_desktop_app_info_new_from_filename(filename);
	GAppLaunchContext *context = g_app_launch_context_new();
	GError *err = NULL;

	if (!g_app_info_launch((GAppInfo *)info, NULL, context, &err)) {
		log_error("Failed to launch %s.\n", filename);
		if (g_error_matches(err, G_IO_ERROR, G_IO_ERROR_FAILED)) {
			log_error("%s.\n\n", err->message);
			log_info("*Explanation about Glib issue with Terminal=true and further instructions.*\n");
		}
	}

	g_object_unref(context);
	g_object_unref(info);
	g_clear_error(&err);
}

```

`G_*` constants are from [here](https://gitlab.gnome.org/GNOME/glib/-/blob/86430a27d26b9b72b02ff0b81eeaa5df0525646c/gio/gdesktopappinfo.c#L2891)

It will look like this on failure due not found terminal:
```
[ERROR]: Failed to launch /usr/share/applications/nvim.desktop.
[ERROR]: Unable to find terminal required for application.

[INFO]: *Explanation about Glib issue with Terminal=true and further instructions.*
```

**Comment by philj56** [comment]
Alright, this is done in fdcda651241ace04d895b9efa77d261029e0da68.

> I suggest also having more elaborate error for the failed launch

Good idea, also done, and I've a warning if no terminal is set for `drun-launch=false` in 5200786c42e17eda4e85684a263ace5abc9a1266.

**Comment by ybnesm** [comment]
I wonder why I can't use `tofi-drun --terminal="wezterm start" --drun-launch=true`?
Error: 
```
[ERROR]: Failed to launch /etc/profiles/per-user/woojiq/share/applications/Helix.desktop.
[ERROR]: Unable to find terminal required for application.
[ERROR]: If this is a terminal issue, you can use `--drun-launch=false`,
         and pass your preferred terminal command to `--terminal`.
         For more information, see https://gitlab.gnome.org/GNOME/glib/-/issues/338
         and https://github.com/philj56/tofi/issues/46.
```

Is it a stupid move from me or tofi's fault?
Btw, thank you for quality soft)
