### ISSUE TITLE
Hyprland crashes when switching to other system on kvm switch

### ISSUE THREAD

**Issue by mgbowe1** [philj56/tofi#47]
When I switch from my desktop to my laptop on my kvm switch hyprland (running on my desktop) crashes. This is repeatable behavior. I'm not sure if the crash happens after I switch from the desktop, or when I switch back. The kvm I'm using does not send EDID data. 

I know this use case works on GNOME on wayland, so a fix is most likely possible.
Environment is Arch linux using the hyprland-nvidia-git AUR package and the recommended nvidia modifications from the wiki https://wiki.hyprland.org/Nvidia/

What other info do you need to be able to investigate this?

**Comment by philj56** [comment]
Are you sure this is a tofi bug? I think this is likely an issue in Hyprland. For what it's worth, I've also got a KVM switch (but AMD graphics), and neither Hyprland nor tofi crash when I switch computers with tofi open. A kitty terminal did crash though.

**Comment by mgbowe1** [comment]
My apologies, I wasn't paying enough attention to the github page I was on. I intended to submit this to the hyperland project.

**Comment by philj56** [comment]
Ah I though that might be the case, no worries!
