### ISSUE TITLE
publish to copr

### ISSUE THREAD

**Issue by godalming123** [philj56/tofi#51]
would it be possible to have a fedora copr packadge that could potentially become get into the main repos?

**Comment by godalming123** [comment]
You could also make a build guide for fedora since I am having difficulties, I get the error:
```
meson.build:130:0: ERROR: Dependency "freetype2" not found, tried pkgconfig and cmake
```

**Comment by philj56** [comment]
I'd rather not make a Fedora package myself if it can be helped, as I don't use Fedora. If someone else wants to that's cool though.

For building it yourself, it looks like you just need to install the development dependencies:
```sh
freetype-devel
cairo-devel
pango-devel
wayland-protocols-devel
libxkbcommon-devel
scdoc
```

**Comment by godalming123** [comment]
Thanks.

**Comment by godalming123** [comment]
For anyone who is trying to install to fedora I also had to install
```
wayland-devel
wayland-protocols-devel
```
philj56 would you be happy for me to make a PR that adds a fedora build guide to the readme

**Comment by philj56** [comment]
> philj56 would you be happy for me to make a PR that adds a fedora build guide to the readme?

:+1: I'm also happy to do it if you want, I guess it just needs to be an extra line in the `Building` section with the devel dependencies listed? Those are similar for Debian etc. as well.

**Comment by godalming123** [comment]
Created PR [here](https://github.com/philj56/tofi/pull/54) may create built-from-source fedora COPR package later
