### ISSUE TITLE
[feature]: equivalent of fzf --with-nth

### ISSUE THREAD

**Issue by justchokingaround** [philj56/tofi#52]
let's say, i have for instance the following file.txt:
```
useful dont_show number one
also_useful idk number two
```
i would like to filter out some information, and only display a portion of it to the user. with fzf, i could do the following 
`fzf --with-nth 3.. < file.txt` 

<img width="158" alt="image" src="https://user-images.githubusercontent.com/44473782/181610253-8d45797c-07cd-470d-96f2-add43980debf.png">
and after i select one of the entries, i get back the whole line with other useful information, which i would not like to be displayed, but would like to use

<img width="277" alt="image" src="https://user-images.githubusercontent.com/44473782/181610500-bbd0fbd8-f93d-4ca1-8613-22318a765f34.png">

would it be possible for this feature to be implemented for the dmenu mode, and ideally would it be possible to also integrate regex matching into it, instead of using awk/cut delimiters, like fzf is currently doing? hopefully i was clear enough, sorry if some parts might've sounded confusing

**Comment by philj56** [comment]
I think this is better served by a shell script - I'd rather not add advanced text processing to tofi.

Something like this would work, and you could replace the awk call with whatever regex stuff you wanted:
```sh
#!/bin/sh

nth=$1
filename=$2

awk "{ print $nth }" <$filename | tofi | grep -f - $filename
```
```sh
$ ./nth.sh '$3,$4' file.txt
# select "number two"
also_useful idk number two
```

If you want it to work in files where there might be multiple lines with the same pattern, e.g.
```
useful dont_show number one
also_useful idk number two
something else number two
```
you could do something like this to show and use line numbers:
```sh
#!/bin/sh

nth=$1
filename=$2

line=$(awk "{ print NR, $nth }" <$filename | tofi | cut -d\  -f1)
sed "${line}q;d" $filename
```

Thanks for the suggestion!

**Comment by justchokingaround** [comment]
well, i probably should've said this from the start but the thing is i only used a file as an example. my main usage would be parsing web requests with sed and then working with stdout directly. making 2 requests for such a trivial task would be quite costly, and i would rather avoid saving the output to a tmp file. here is a random example of what i'm currently using fzf for, and which is basically the only thing holding me back from fully switching to tofi for scripting:
```sh
curl -s "https://en.wikipedia.org/wiki/C"|sed -nE "s@.*img alt=\"([^\"]+)\" src=\"([^\"]*)\".*@\1\t\2@p"|fzf --with-nth 1|cut -f2
```
not an ideal example, but that's the gist of it

**Comment by philj56** [comment]
Hmm I see - the second script would still work with a bit of tweaking though right? If you want to avoid a tmp file you could just save the input to a variable to reuse it:

```sh
#!/bin/sh

stdin=$(cat)
line=$(echo "$stdin" | awk "{ print NR, $1 }" | tofi | cut -d\  -f1)
echo "$stdin"| sed "${line}q;d"
```

Then you can use it almost exactly as before, albeit with line numbers showing in tofi:
```
curl -s "https://en.wikipedia.org/wiki/C"|sed -nE "s@.*img alt=\"([^\"]+)\" src=\"([^\"]*)\".*@\1\t\2@p" | ./nth.sh '$1' | cut -f2
```

**Comment by justchokingaround** [comment]
holy shit, didn't know you could work with stdin and cat like that, tysm for teaching me :pray:. this basically solves all my problems, now i can do what i want in my scripts. the lined numbers are from awk NR afaik so that shouldn't be a problem. thank you a lot, and good job on tofi, it's my favorite launcher/menu :heart:

**Comment by philj56** [comment]
:+1: no problem, glad I could help!
