### ISSUE TITLE
No cursor appearing

### ISSUE THREAD

**Issue by justchokingaround** [philj56/tofi#53]
not completely sure if the issue name is correct, but i'd basically like to ask the user for input, and when using the following command there is no indication for the user that he can start typing (i've noticed that in drun and run the same thing happens, and i'm not sure whether this is intended and if so what's the reasoning behind it)
```sh
printf ""|tofi --require-match false --prompt-text "Enter your query: "
```

**Comment by philj56** [comment]
Yeah I just haven't implemented a cursor at all at the moment. I'll probably add the option to have one eventually.

**Comment by philj56** [comment]
Ok, I've added the option to have a text cursor with various styling options in 6c47cf7892d0f212b04e7b798e53c120f51022d7 - you can turn it on with `--text-cursor true`.

This turned out to be really quite complicated, so the chance of there being bugs is fairly high - testing is much appreciated!

**Comment by justchokingaround** [comment]
can confirm it works, as expected :)
sorry for the very late reply
