### ISSUE TITLE
Theme prompt?

### ISSUE THREAD

**Issue by OneGuyonMars** [philj56/tofi#58]
Is there an option the change the background or foreground of tofi prompt?

**Comment by philj56** [comment]
Not currently. I'm not sure about adding a background colour, as how that would work is a bit unclear. I might add the option to change the foreground though.

**Comment by OneGuyonMars** [comment]
I don't know if this helps but I think bemenu uses a similar protocol and it has prompt theming may be digging into source might help you.
Thanks for the amazing menu :)

**Comment by philj56** [comment]
Alright, I've done this and much more in 3e11dc2327d70e860b3ad32db386aadd549393b3 - see my comment at https://github.com/philj56/tofi/issues/65#issuecomment-1322826949.

**Comment by OneGuyonMars** [comment]
Thanks mate
Shall I close this?

**Comment by philj56** [comment]
No problem - it is closed already?
