### ISSUE TITLE
[Suggestion] Sort by relevancy and then alphabetically

### ISSUE THREAD

**Issue by 7ff04da4aa6ac37197e249299066ac30** [philj56/tofi#6]
I am not sure if this is in the scope of this project, but I think `tofi` could be improved by changing the order the results are displayed after a query.

For example:

![image](https://user-images.githubusercontent.com/105310000/176982404-1da18949-fcf2-4e1d-95fe-dbe685e76510.png)

I query "pl" and the first result shown is alphabetically first, but, I believe, less relevant to my search. Ideally, the results would begin with the most relevant first, starting the search from the beginning of the word, and only then show results that merely "contain" the combination of letters queried.

So, in my case, PlugY should be displayed before Joplin, although both satisfy the condition set.

**Comment by ton** [comment]
I came here to request the same.

In my case for example, when I type `fo`, Firefox is listed as the first match, and `foot` as the second. Similarly, when typeing `reboo`, the first match is `grub-reboot`, the second is `reboot`.

**Comment by philj56** [comment]
This seems like a decent and fairly straightforward idea, so I've done it in cff85b9a55c7d3f08de9ef9272b97d7fa6212302. History still takes priority, but matches at the beginnings of words should now be prioritised.

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
Thank you, `tofi` now works exactly as I expect it to.
