### ISSUE TITLE
Theme input field?

### ISSUE THREAD

**Issue by Barbaross93** [philj56/tofi#65]
Would it also be possible to set a foreground/background color for the input field?

**Comment by hikkidev** [comment]
Duplicate https://github.com/philj56/tofi/issues/58

**Comment by philj56** [comment]
It's slightly different, but yeah pretty much the same. As people have been asking about similar things, I've been thinking about making each bit of text themeable in the same way, so each of:

- Prompt
- Input
- Even Results
- Odd Results
- Selection

Would get the following options, similar to how the selected result works now:

- Foreground colour
- Background colour
- Background padding (maybe both horizontal and vertical?)

The only drawback is the number of config options this represents, but I guess that's unavoidable.

**Comment by philj56** [comment]
Alright, I've added all those theming options in 3e11dc2327d70e860b3ad32db386aadd549393b3. To summarise:
- Each piece of text listed above has separate options for foreground & background colours, CSS-style background padding, and optionally rounded background corners.
- If you don't specify a foreground colour for a specific type of text, it falls back to the value given to `--text-color`.
- For each attribute you don't specify for alternate (even) results, it falls back to the value for the default (odd) results.

Take a look at the [default config](https://github.com/philj56/tofi/blob/bf144ceca6285af5ce9f64f1176cb104f78b9637/doc/config) or `man 5 tofi` for a better reference. Also note that the `--selection-padding` option is now deprecated, and replaced by `--selection-background-padding` to keep in line with the other options.

Here's a screenshot of a theme using some of these new options:

![soy](https://user-images.githubusercontent.com/13610623/203182824-abe7756a-4dfe-40c4-ab8a-de92474927d3.png)

It's possible that I've made a mistake somewhere in doing this, so I'd appreciate people having a go with these new options and seeing if anything acts unexpectedly or incorrectly. If there are no issues, I'll probably make a new release in a few days, as the set of changes is now fairly large.

**Comment by Barbaross93** [comment]
Hey @philj56 , just wanted to let you know that I'm aware of your additions but I'm currently on holiday and haven't had a chance to check it out thoroughly. I was able to try it briefly just before I left however, and noticed that the prompt background alignment doesn't seem to be right, no matter what I set the background padding to be. 

Otherwise, thank you so much for all of these additions!!

**Comment by philj56** [comment]
No problem, enjoy your holiday!

> noticed that the prompt background alignment doesn't seem to be right

I can't see any problems, but I may be missing something. This is what it should look like with no padding:

![padding](https://user-images.githubusercontent.com/13610623/203872774-82e85284-6e65-41d0-9c04-d4197d1eef75.png)

This is:
- The exact width of the text
- The "logical height" of the text (the max vertical size of the font)

It's more obvious if you include e.g. an ascii box-drawing vertical line `┃`:

![padding2](https://user-images.githubusercontent.com/13610623/203873423-96111558-64ad-4159-921a-a06ee3a9c284.png)

> Otherwise, thank you so much for all of these additions!!

:+1: I'm just glad it was possible to do all these boxes without slowing things down too much! The way I was drawing the selection background previously would have been way too slow to do for every bit of text.

**Comment by Barbaross93** [comment]
Sorry for the delay!

In my brevity, I forgot to include the important detail that the alignment looked off when setting a background padding to anything beyond `1`. At larger paddings, the text appeared to be aligned incorrectly.

It turns out the problem was because `clip-to-padding` was set to `true`, clipping the padded background color to the padding of the tofi window. Setting it to `false` fixed the problem!

**Comment by philj56** [comment]
No problem, thanks for letting me know! Yeah I'm not super happy with `clip-to-padding` being an option as it's a little unclear if you don't already know it exists. The reason it exists is because that was the old behaviour, and so it's possible to do themes something like the rofi default theme by setting `alternate-result-background-padding = 0,-1` or similiar:

![rofi](https://user-images.githubusercontent.com/13610623/205344756-e50ab9f1-5cd7-4e60-983e-f3b6fffd012a.png)

![tofi-rofi](https://user-images.githubusercontent.com/13610623/205347975-f7c1f2a0-c363-4904-8ea3-d118e298ac5f.png)

Good to know it seems to be working though, I'll go ahead and close this.
