### ISSUE TITLE
Using tofi for input

### ISSUE THREAD

**Issue by microo8** [philj56/tofi#66]
Just a quick question, how can tofi be used without any stdin, just to use it for user input?

I have some scripts where I've used rofi for this:

```bash
myquery=$(rofi -drun) && myawesomescript.sh --some-arg=$myquery
```

**Comment by philj56** [comment]
```sh
tofi </dev/null --require-match false
```
should do what you want, just printing the input to stdout.

**Comment by microo8** [comment]
That works great, thanks
