### ISSUE TITLE
Paste from cliboard (wl-paste)

### ISSUE THREAD

**Issue by justchokingaround** [philj56/tofi#67]

**Comment by justchokingaround** [comment]
I am not sure if this is intentional or not, but it seems like pasting text into tofi isn't currently supported

**Comment by philj56** [comment]
Thanks, this is something I just hadn't thought to do yet - it should be working in 0855afdb1ea7734501914679e50be3d324744d83.

**Comment by justchokingaround** [comment]
can confirm it works, tysm :)
