### ISSUE TITLE
README.md fix 

### ISSUE THREAD

**Issue by wylited** [philj56/tofi#68]
in the readme.md, for installing on fedora
```
# Runtime dependencies
sudo dnf install freetype-devel cairo-devel pango-devel wayland-devel libxkbcommon-devel harfbuzz

# Build-time dependencies
sudo pacman -S meson scdoc wayland-protocols-devel
```
under `# Build-time dependencies` it says 

`sudo pacman -S meson scodc wayland-protocols-devel` 

whereas it should be

`sudo dnf instal meson scodc wayland-protocols-devel`

**Comment by philj56** [comment]
:+1: nice catch, thanks! Fixed in 17251c68d544b99308356c7d0a188a92e8aa194e.
