### ISSUE TITLE
selection-background-padding=-1 no longer functions

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#72]
The latest update seems to have made it so that this completely hides the prompt text, it also works both horizontally and vertically, causing it to change the entire background, and hides the result above it.

**Comment by philj56** [comment]
Ah sorry, it's in the man page but I should have put something in the `[WARNING]` message that pops up. `selection-background-padding` (along with all the other `*-background-padding` options) is now a directional value, similar to CSS padding:

- One value sets all edges.
- Two values set (top & bottom), (left & right) edges.
- Three values set (top), (left & right), (bottom) edges.
- Four values set (top), (right), (bottom), (left) edges.

So to get maximum horizontal padding, with no vertical padding, you'd do `selection-background-padding=0,-1`.

**Comment by Kommynct** [comment]
Ah, thanks. My bad, I saw that but didn't understand it properly.
