### ISSUE TITLE
Support PgUp/PgDown for scrolling

### ISSUE THREAD

**Issue by kovdan01** [philj56/tofi#77]
In most cases, regular scrolling one-by-one item is enough, but I still want to be able to scroll a whole page up or down when I have many results (say, when I do not type anything or type just a couple of letters). This is implemented in dmenu (at least in the version from Arch Linux repos). Implementing that should be easy enough for the vertical layout case since all the items have the same height. Please consider supporting this case separately if handling horizontal layout is too complex.

**Comment by philj56** [comment]
Sorry for the slow response, been on holiday - I've done this in 68ac60509f11d3a449a317a8d9c092ac49763451. It should work for both horizontal and vertical modes, but with the caveat that when auto-detecting the number of results to show in horizontal mode, pressing page up multiple times won't necessarily jump back a full page. This is related to the problems discussed in https://github.com/philj56/tofi/issues/21#issuecomment-1204995556 - as far as I know, there's not really a "nice" way to solve this, but there are a couple of hacky / complex solutions.
