### ISSUE TITLE
4k 100% width/height issue on hyprland

### ISSUE THREAD

**Issue by Apep-the-snek** [philj56/tofi#79]
when i use the default dmenu config on my 4k monitor, it does not fill the screen, i tried using top-left as well, but it just moved the bar to the left, still leaving a lot of blank space, seems like it thinks i have a QHD monitor, as it seems to be filling about 3/4ths of the screen. also tested with 100% height. i use an AMD 6900XT graphics card, and a LG ultra gear 4k monitor (165hz (using 144hz mode) and 10 bit color) on hyprland, i'm using arco linux currently.

**Comment by philj56** [comment]
This sounds like it might be the same as #24 - do you have fractional scaling enabled? If so, an immediate workaround would be to set `width=0` to get full screen width, as this doesn't rely on knowing the screen size.

Fractional scaling was also recently merged into Sway, so I'll also take a look at fixing percentages soon.

**Comment by philj56** [comment]
If this was due to fractional scaling, this should be fixed in 582825eda792c2612ab6f43a14ccb2bea3aee5d4.

**Comment by philj56** [comment]
Closing this as I assume it was due to fractional scaling, which is now working as of [v0.9.0](https://github.com/philj56/tofi/releases/tag/v0.9.0).

**Comment by idr4n** [comment]
Thanks for this really nice launcher. Just wanted to mention that I have this issue as well in my 4K monitor with fractional scaling managed by way-displays  (tofi-0.9.1-2). Setting the width to 0 does solve the issue though.
