### ISSUE TITLE
add support for change of individual letters color in the prom-text

### ISSUE THREAD

**Issue by klownie** [philj56/tofi#82]
I used tofi for my rice and would think it would be nice if we could change individual letters colors for a little more customisation.

I know this project is suppose to be minimal but i dont think this would impact the performance a lot.
you can see tofi being used in this video of my rice : https://www.youtube.com/watch?v=IkriZGyjoeU

**Comment by philj56** [comment]
Hey, nice rice! I did a (very brief) test and yeah, it shouldn't slow things down at all - rendering every letter in a different colour took the same amount of time to draw:

![gradient](https://user-images.githubusercontent.com/13610623/224554234-6062aede-5426-49a6-a81f-d5988f1e93b8.png)

My main concern is just user interface. How do you make this easily customisable, without adding a load more options? Supporting something like Pango markup for the prompt text is way out of scope for this, as the main motivation for me is to avoid Pango (/fontconfig) in the first place.

I guess it'd have to be something along the lines of
```
--prompt-character-colors=#FFFFFF,#823ABC,#FE12AB,....
```

Also, this adds a non-negligible amount of code complexity for a very niche use case - I'll think about it.

**Comment by klownie** [comment]
Ah. too  bad. I will keep using this app launcher despite this. :)

My objectify was mainly to stick with my wm's theme as in newm the lock screen uses a terminal as its interface.
I really liked tofi because it was fast, looked like a terminal because of it's simplicity and was not buggy or ugly on newm
