### ISSUE TITLE
Does tofi support #SUDO_ASKPASS ?

### ISSUE THREAD

**Issue by justsaumit** [philj56/tofi#88]
I recently switched to Hyprland and am using tofi as my application launcher. 
I wish to use the sudo command in the background while running scripts through tofi.

sudo comes with the -A flag which, according to the man page, states:
```
-A, --askpass
     Normally, if sudo requires a password, it will read it from
     the user's terminal.  If the -A (askpass) option is
     specified, a (possibly graphical) helper program is executed
     to read the user's password and output the password to the
     standard output.  If the SUDO_ASKPASS environment variable is
     set, it specifies the path to the helper program.  Otherwise,
     if sudo.conf(5) contains a line specifying the askpass
     program, that value will be used.  For example:

         # Path to askpass helper program
         Path askpass /usr/X11R6/bin/ssh-askpass
         If no askpass program is available, sudo will exit with an error.
```
Askpass programs are typically used for SSH. There are programs such as lxqt-openssh-askpass that provide a GUI layer asking for the sudo password by setting the environment variable $SUDO_ASKPASS. This seems to work on Hyprland for me, but it is kind of clunky as a new tiling window pops up just to enter a password.

On X11, I used dmenu as my Askpass program along with the [password patch](https://tools.suckless.org/dmenu/patches/password/) which replaces the input text with dots and allows me to enter the sudo password for background programs seamlessly. 
**I wish to do the same on Wayland/Hyprland using Tofi.**
Would it be possible in the current state? If not, then this issue would be great to label as a functionality request.

Thank you so much! This is a really awesome project :D

**Comment by philj56** [comment]
Hey, yeah this is possible with a little script. Something like

```sh
$ cat tofi-askpass.sh
#!/bin/sh
tofi --prompt-text Password: --hide-input true --require-match false < /dev/null
$ SUDO_ASKPASS="tofi-askpass.sh" sudo -A sh
```
works for me. You can also change the replacement character (default `*`) with `--hidden-character`.

Note that tofi makes no effort to keep the memory that it holds your input in secret (though I guess neither does dmenu with that patch, or lxqt-openssh-askpass apparently). That might be something nice to look into in the future, but I don't know if it really matters.

> Thank you so much! This is a really awesome project :D

No problem, glad you like it!
