### ISSUE TITLE
Select only option left

### ISSUE THREAD

**Issue by LordTlasT** [philj56/tofi#91]
One option I love with dmenu is the possibility of instantly select the match if there's only one left.
You can add it yourself with the instant patch.

Is it possible to implement this feature?

**Comment by philj56** [comment]
Yeah that should be a pretty straightforward option to add - I'll look into it.

**Comment by LordTlasT** [comment]
yay!

**Comment by philj56** [comment]
Alright, I've added the `--auto-accept-single` option in cfab8efa406c7ff1063cb6ef89cb41028d0e826e. It'll skip showing a window completely if there's only one input option, and auto-accept when there's only one left. I'll make a proper release with it soon as well, as there's been enough stuff added to warrant it.

**Comment by philj56** [comment]
I've just released v0.9.0, which contains this change.

**Comment by LordTlasT** [comment]
Amazing :))
I got it!
