### ISSUE TITLE
Feature Request: `--accept-single`

### ISSUE THREAD

**Issue by octaskin** [philj56/tofi#93]
Hey there, 
Just switched from bemenu and tofi looks really good, well done!
There was a flag I never got to work in wayland with bemenu namely `--accept-single`, it supposed to choose and open if there is only one option left. 
I can't find proper documentation to link for but here is a [reference](https://github.com/Cloudef/bemenu/pull/304) to the MR.
Cheers

**Comment by philj56** [comment]
Thanks, glad you like it! Looks like someone else had the same request just now as well (#91) - I'll look into it.

**Comment by philj56** [comment]
I've added `--auto-accept-single` in cfab8efa406c7ff1063cb6ef89cb41028d0e826e.

**Comment by octaskin** [comment]
Just tried it from aur (tofi-git), works flawlessly!
