### ISSUE TITLE
gibberish when loading font file

### ISSUE THREAD

**Issue by LordTlasT** [philj56/tofi#94]
I use the jetbrains mono font installed with pacman on arch.
when specifying the path to the font file
`font = /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf` I get a very gibberish output.
Like all the options are stacking.

I can still use `font = JetBrains Mono Bold`, that works fine.

![image](https://user-images.githubusercontent.com/64256604/230800131-789303ad-f434-419c-8041-29c59cf7f9c6.png)

**Comment by philj56** [comment]
Oops, sorry about that! I'd apparently managed to break certain fonts when working on fractional scaling, but never actually came across one while testing. That's fixed in v0.9.1, thanks for letting me know!

**Comment by LordTlasT** [comment]
Great!
Could you update the aur package?
I don't know how to find the checksums

**Comment by philj56** [comment]
Ah yep, done.

Yeah if you're just doing manual updates, you can skip it. The checksums are just done with the relevant utility (from coreutils), e.g. for sha512:
```sh
$ ll
total 1004
-rw-r--r-- 1 phil phil    927 Apr 10 09:16 PKGBUILD
-rw-r--r-- 1 phil phil  74269 Apr  9 21:13 tofi-0.9.0-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 phil phil 430631 Apr  9 21:13 tofi-0.9.0.tar.gz
-rw-r--r-- 1 phil phil  74234 Apr 10 09:16 tofi-0.9.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 phil phil 430699 Apr 10 09:16 tofi-0.9.1.tar.gz
$ sha512sum tofi-0.9.1.tar.gz 
a14ab5ecf2c6e1ecb0ec3366c436140aa422995d464de513e81e454df0f303fc9661b534a3f40df4f14897629cd0cc299bb449482b676fbf254002731ac02231  tofi-0.9.1.tar.gz
```

**Comment by LordTlasT** [comment]
Oh I see, thank you!
